name: iOS Cucumberworkflow

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  upload-reports:
    name: Upload verification reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set paths
        id: set_paths
        run: |
          path_system="${{ github.sha }}/system"
          path_item="${{ github.sha }}/item"
          echo "path_system=$path_system" >> $GITHUB_ENV
          echo "path_item=$path_item" >> $GITHUB_ENV
      - name: Create Dummy Verification Test Files
        run: |
          mkdir -p "$path_system"  # Create the directory structure
          mkdir -p "$path_item"  # Create the directory structure
          echo '{"owner": '${{ github.repository_owner }}', "repository": '${{ github.repository }}', "branch": '${{ github.ref_name }}', "sha": '${{ github.sha }}', "verification": "system", "timestamp": '$(date +%s)'}' > "$path_system/cucumber-messages.ndjson"
          echo '{"owner": '${{ github.repository_owner }}', "repository": '${{ github.repository }}', "branch": '${{ github.ref_name }}', "sha": '${{ github.sha }}', "verification": "item", "timestamp": '$(date +%s)'}' > "$path_item/junit.xml"
        env:
          path_system: ${{ env.path_system }}
          path_item: ${{ env.path_item}}
      - name: Upload System Verificaiton
        id: upload-system-ver
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'system-verification'
          type: 'bdd'
          format: 'cucumber+ndjson'
          hostname: ${{ vars.UPLOAD_JOB }}
          path: '${{ env.path_system }}/**'
      - name: Upload Item Verificaiton
        id: upload-item-ver
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'item-verification'
          type: 'test'
          format: 'junit'
          hostname: ${{ vars.UPLOAD_JOB }}
          path: '${{ env.path_item }}/**'
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create path
        id: set_paths
        run: |
          path_sbom="${{ github.sha }}/sbom"
          mkdir -p $path_sbom # Create the directory structure
          echo "path_sbom=$path_sbom" >> $GITHUB_ENV
          echo "Created path at $path_sbom"
          path_test_reports="${{ github.sha }}/test-reports"
          mkdir -p $path_test_reports # Create the directory structure
          echo "path_test_reports=$path_test_reports" >> $GITHUB_ENV
          echo "Created path at $path_test_reports"
      - name: Set up Ruby for xcpretty
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Install xcpretty  
        run: |
          gem install xcpretty
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install CDXGen and build SBOM
        run: |
          npm install -g @cyclonedx/cdxgen
          cdxgen -t swift -o ${{ env.path_sbom }}/bom.json -p --spec-version 1.6
        env:
          path_sbom: ${{ env.path_sbom }}
      - name: Upload SBOM
        id: upload-sbom
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'cybersecurity'
          type: 'sbom'
          format: 'cyclonedx'
          hostname: ${{ vars.UPLOAD_JOB }}
          path: '${{ env.path_sbom }}/**'
      - name: Test
        id: run-tests
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
          TARGET_DEVICE_PLATFORM_NAME: ${{ 'iphonesimulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" 
          build_settings=$(xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -showBuildSettings)
          output_dir=$(echo "$build_settings" | awk '/BUILD_ROOT/ {print $3}')
          echo "Output directory: $output_dir"
          find $output_dir -type f -name "*.xcresult" -exec sh -c 'cat "$1" | xcpretty --report junit --output "${ENV_PATH_TEST_REPORTS}"' sh {} \;
          ls -l ${{ env.path_test_reports }}
          # Retrieve TARGETNAME dynamically
          TARGETNAME=$(xcodebuild -list | grep -A 1 "Targets:" | tail -n 1 | awk '{$1=$1;print}')
          echo "TARGETNAME=$TARGETNAME"
          
          report_file=$(find ~/Library/Developer/CoreSimulator/Devices/$TARGET_DEVICE_IDENTIFIER -name "CucumberTestResultsForCucumberSwiftSampleUITests.json" -print0 | xargs -r -0 ls -1 -t | head -1)
          echo "Report file: $report_file"
          echo "::set-output name=report_file::$report_file"
      - name: Upload Cucumber Test Results
        uses: actions/upload-artifact@v4
        with:
         name: cucumber-test-results
         path: ${{ steps.run-tests.outputs.report_file }}
         
